# Main server options
[server]
address = 127.0.0.1
port = 4455

# field is one of sender/sasl_username/client_address
field = sender
default_limit = 5/day
action = DEFER
action_text = Limit ({limit}) exceeded for {field}={key}

# storage: this or memory:// (default) for memory storage
storage = redis://localhost:6379/

dump_period = 60
dump_file = /var/lib/postfixlimit/limits.txt
log_file = /var/log/postfixlimit/postfixlimit.log

# Specific limits
[limits]
aaa@example.com = 100 / day
